Excercise 6. An array is entered from the keyboard. Replace all non-zero elementswith -1.<br>
Excercise 7. An array is entered from the keyboard. Replace all zeros with -1.<br>
Excercise 9. Enter the number n. Create an array of values from n to 0.<br>
Excercise 10. Enter the numbers n and m. Create an array of random values of size
nхn and calculate the minimum, maximum value, mean and standard deviation, rounded to 3 decimal places.<br>
Excercise 11. Create an array of 1 of size nхn and add to it a "border" formed from 0.<br>
Excercise 15. Arrange 1 and 0 on the 8х8 field in a checkerboard pattern using the numpy tile().<br>
Excercise 17. Fill the vector with values from 0 to n. Replace all values greater than n/2 and less than 3n/4 with zeros.<br>
Excercise 18. Fill the vector with values from 0 to n. Replace signs for all values less than n/2 and greater than 3n/4 to opposite ones.<br>
Excercise 20. Generate a vector of n elements that are evenly spaced on the interval (0,1) i.e. both ends of the interval are not included. Output values up to 3 decimal places.<br>
Excercise 22. Enter the numbers n and m. Generate a matrix nхn of random integer elements from 0 to m. Change the signs of all maximum elements to the opposite.<br> 

In [2]:
import numpy as np


def task_6():
    arr = np.array([1, 2, 3, 4, 5])
    new_arr = np.where(arr != 0, np.array([-1]), arr)
    print(np.allclose(new_arr, np.array([-1, -1, -1, -1, -1])))

    arr = np.array([0, 0, 0, 0, 0])
    new_arr = np.where(arr != 0, np.array([-1]), arr)
    print(np.allclose(new_arr, np.array([0, 0, 0, 0, 0])))

    arr = np.array([0, 1, 2, 3, 0, 4, 0, 0, 5, 6])
    new_arr = np.where(arr != 0, np.array([-1]), arr)
    print(np.allclose(new_arr, np.array([0, -1, -1, -1, 0, -1, 0, 0, -1, -1])))


def task_7():
    arr = np.array([1, 2, 3, 4, 5])
    new_arr = np.where(arr == 0, np.array([-1]), arr)
    print(np.allclose(new_arr, np.array([1, 2, 3, 4, 5])))

    arr = np.array([0, 0, 0, 0, 0])
    new_arr = np.where(arr == 0, np.array([-1]), arr)
    print(np.allclose(new_arr, np.array([-1, -1, -1, -1, -1])))

    arr = np.array([0, 1, 2, 3, 0, 4, 0, 0, 5, 6])
    new_arr = np.where(arr == 0, np.array([-1]), arr)
    print(np.allclose(new_arr, np.array([-1, 1, 2, 3, -1, 4, -1, -1, 5, 6])))


def task_9():
    n = 5
    arr = np.arange(n, -1, -1)
    print(np.allclose(arr, np.array([5, 4, 3, 2, 1, 0])))

    n = 3
    arr = np.arange(n, -1, -1)
    print(np.allclose(arr, np.array([3, 2, 1, 0])))

    n = 10
    arr = np.arange(n, -1, -1)
    print(np.allclose(arr, np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0])))


def task_10():
    m, n = 3, 3
    arr = np.random.rand(m, n)
    print('Array:\n', arr)
    print('min: ', np.round(np.min(arr), 3))
    print('max: ', np.round(np.max(arr), 3))
    print('mean: ', np.round(np.mean(arr), 3))
    print('deviation: ', np.round(np.std(arr), 3))

    m, n = 6, 2
    arr = np.random.rand(m, n)
    print('Array:\n', arr)
    print('min: ', np.round(np.min(arr), 3))
    print('max: ', np.round(np.max(arr), 3))
    print('mean: ', np.round(np.mean(arr), 3))
    print('deviation: ', np.round(np.std(arr), 3))


def task_11():
    n = 2
    x = np.ones((n, n))
    x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
    print(np.allclose(x, np.array([[0., 0., 0., 0.],
                                   [0., 1., 1., 0.],
                                   [0., 1., 1., 0.],
                                   [0., 0., 0., 0.]]
                                  )))

    n = 3
    x = np.ones((n, n))
    x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
    print(np.allclose(x, np.array([[0., 0., 0., 0., 0.],
                                   [0., 1., 1., 1., 0.],
                                   [0., 1., 1., 1., 0.],
                                   [0., 1., 1., 1., 0.],
                                   [0., 0., 0., 0., 0.]]
                                  )))


def task_15():
    # n is twice smaller then board size
    n = 3
    checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (n, n))
    print(np.allclose(checkerboard, np.array([[0, 1, 0, 1, 0, 1],
                                              [1, 0, 1, 0, 1, 0],
                                              [0, 1, 0, 1, 0, 1],
                                              [1, 0, 1, 0, 1, 0],
                                              [0, 1, 0, 1, 0, 1],
                                              [1, 0, 1, 0, 1, 0]]
                                             )))

    n = 2
    checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (n, n))
    print(np.allclose(checkerboard, np.array([[0, 1, 0, 1],
                                              [1, 0, 1, 0],
                                              [0, 1, 0, 1],
                                              [1, 0, 1, 0]]
                                             )))


def task_17():
    n = 10
    arr = np.arange(n + 1)
    new_arr = np.where(((arr >= n / 2) & (arr <= 3 * n / 4)), np.array([0]), arr)
    print(np.allclose(new_arr, np.array([0, 1, 2, 3, 4, 0, 0, 0, 8, 9, 10])))

    n = 15
    arr = np.arange(n + 1)
    new_arr = np.where(((arr >= n / 2) & (arr <= 3 * n / 4)), np.array([0]), arr)
    print(np.allclose(new_arr, np.array([0, 1, 2, 3, 4, 5, 6, 7, 0, 0, 0, 0, 12, 13, 14, 15])))

    n = 5
    arr = np.arange(n + 1)
    new_arr = np.where(((arr >= n / 2) & (arr <= 3 * n / 4)), np.array([0]), arr)
    print(np.allclose(new_arr, np.array([0, 1, 2, 0, 4, 5])))


def task_18():
    n = 10
    arr = np.arange(n + 1)
    new_arr = np.where(((arr < n / 2) | (arr > 3 * n / 4)), -arr, arr)
    print(np.allclose(new_arr, np.array([0, -1, -2, -3, -4, 5, 6, 7, -8, -9, -10])))

    n = 15
    arr = np.arange(n + 1)
    new_arr = np.where(((arr < n / 2) | (arr > 3 * n / 4)), -arr, arr)
    print(np.allclose(new_arr, np.array([0, -1, -2, -3, -4, -5, -6, -7, 8, 9, 10, 11, -12, -13, -14, -15])))

    n = 5
    arr = np.arange(n + 1)
    new_arr = np.where(((arr < n / 2) | (arr > 3 * n / 4)), -arr, arr)
    print(np.allclose(new_arr, np.array([0, -1, -2, 3, -4, -5])))


def task_20():
    n = 5
    arr = np.round(np.linspace(0.0, 1.0, num=n + 1, endpoint=False)[1:], 3)
    print(np.allclose(arr, np.array([0.167, 0.333, 0.5, 0.667, 0.833])))

    n = 10
    arr = np.round(np.linspace(0.0, 1.0, num=n + 1, endpoint=False)[1:], 3)
    print(np.allclose(arr, np.array([0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818, 0.909])))

    n = 15
    arr = np.round(np.linspace(0.0, 1.0, num=n + 1, endpoint=False)[1:], 3)
    print(np.allclose(arr, np.array([0.062, 0.125, 0.188, 0.25, 0.312, 0.375, 0.438, 0.5, 0.562, 0.625, 0.688, 0.75,
                                     0.812, 0.875, 0.938]
                                    )))


def task_22():
    n, m = 4, 8
    arr = np.random.randint(0, m, (n, n))
    print('Initial vector\n', arr)
    new_arr = np.where(arr == np.max(arr), -arr, arr)
    print('Modified vector\n', new_arr)

    n, m = 3, 5
    arr = np.random.randint(0, m, (n, n))
    print('Initial vector\n', arr)
    new_arr = np.where(arr == np.max(arr), -arr, arr)
    print('Modified vector\n', new_arr)

    n, m = 4, 3
    arr = np.random.randint(0, m, (n, n))
    print('Initial vector\n', arr)
    new_arr = np.where(arr == np.max(arr), -arr, arr)
    print('Modified vector\n', new_arr)


print('task 6')
task_6()
print('task 7')
task_7()
print('task 9')
task_9()
print('task 10')
task_10()
print('task 11')
task_11()
print('task 15')
task_15()
print('task 17')
task_17()
print('task 18')
task_18()
print('task 20')
task_20()
print('task 22')
task_22()

task 6
True
True
True
task 7
True
True
True
task 9
True
True
True
task 10
Array:
 [[0.00808203 0.11852027 0.04770698]
 [0.30243787 0.5125434  0.21752857]
 [0.09400056 0.71890619 0.48541558]]
min:  0.008
max:  0.719
mean:  0.278
deviation:  0.231
Array:
 [[0.47483181 0.55090492]
 [0.03646319 0.56512252]
 [0.80455444 0.2869563 ]
 [0.64092469 0.37553124]
 [0.80328583 0.95215501]
 [0.83859237 0.93251349]]
min:  0.036
max:  0.952
mean:  0.605
deviation:  0.268
task 11
True
True
task 15
True
True
task 17
True
True
True
task 18
True
True
True
task 20
True
True
True
task 22
Initial vector
 [[1 1 6 1]
 [7 7 0 3]
 [6 5 2 2]
 [3 6 6 5]]
Modified vector
 [[ 1  1  6  1]
 [-7 -7  0  3]
 [ 6  5  2  2]
 [ 3  6  6  5]]
Initial vector
 [[1 3 4]
 [3 3 0]
 [0 3 4]]
Modified vector
 [[ 1  3 -4]
 [ 3  3  0]
 [ 0  3 -4]]
Initial vector
 [[1 0 1 2]
 [2 1 0 2]
 [0 1 0 2]
 [1 1 0 2]]
Modified vector
 [[ 1  0  1 -2]
 [-2  1  0 -2]
 [ 0  1  0 -2]
 [ 1  1  0 -2]]


In [1]:
import numpy as np


def task_6():
    try:
        arr = np.array([int(i) for i in input('Enter array separated by spaces: ').strip().split(' ')])
    except ValueError:
        print('Incorrect array')
    else:
        new_arr = np.where(arr != 0, np.array([-1]), arr)
        print('Array: ', new_arr)


def task_7():
    try:
        arr = np.array([int(i) for i in input('Enter array separated by spaces: ').strip().split(' ')])
    except ValueError:
        print('Incorrect array')
    else:
        new_arr = np.where(arr == 0, np.array([-1]), arr)
        print('Array: ', new_arr)


def task_9():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number!')
    else:
        arr = np.arange(n, -1, -1)
        print('Array: ', arr)


def task_10():
    try:
        n, m = [int(i) for i in input('Enter 2 positive numbers separated by spaces: ').strip().split(' ')]
        if n <= 0 or m <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect numbers')
    else:
        arr = np.random.rand(m, n)
        print('Array:\n', arr)
        print('min: ', np.round(np.min(arr), 3))
        print('max: ', np.round(np.max(arr), 3))
        print('mean: ', np.round(np.mean(arr), 3))
        print('deviation: ', np.round(np.std(arr), 3))


def task_11():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number')
    else:
        x = np.ones((n, n))
        x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
        print(x)


def task_15():
    # n is twice smaller then board size
    n = 4
    if n >= 0:
        checkerboard = np.tile(np.array([[0, 1], [1, 0]]), (n, n))
        print(checkerboard)
    else:
        print('n is incorrect', n)


def task_17():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number')
    else:
        arr = np.arange(n + 1)
        print('Array: ', arr)
        new_arr = np.where(((arr >= n / 2) & (arr <= 3 * n / 4)), np.array([0]), arr)
        print('Replace all values greater than n/2 and less than 3n/4 with zeros: n =', n)
        print(new_arr)


def task_18():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number')
    else:
        arr = np.arange(n + 1)
        print('Array: ', arr)
        new_arr = np.where(((arr < n / 2) | (arr > 3 * n / 4)), -arr, arr)
        print(' Replace signs for all values less than n/2 and greater than 3n/4 to opposite ones: n =', n)
        print(new_arr)


def task_20():
    try:
        n = int(input('Enter positive number: '))
        if n <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect number')
    else:
        arr = np.round(np.linspace(0.0, 1.0, num=n + 1, endpoint=False)[1:], 3)
        print('Array: ', arr)


def task_22():
    try:
        n, m = [int(i) for i in input('Enter 2 positive numbers separated by spaces: ').strip().split(' ')]
        if n <= 0 or m <= 0:
            raise ValueError
    except ValueError:
        print('Incorrect numbers')
    else:
        arr = np.random.randint(0, m, (n, n))
        print('Initial vector\n', arr)
        new_arr = np.where(arr == np.max(arr), -arr, arr)
        print('Modified vector\n', new_arr)


print('task 6')
task_6()
print('task 7')
task_7()
print('task 9')
task_9()
print('task 10')
task_10()
print('task 11')
task_11()
print('task 15')
task_15()
print('task 17')
task_17()
print('task 18')
task_18()
print('task 20')
task_20()
print('task 22')
task_22()

task 6
Enter array separated by spaces: 5 5
Array:  [-1 -1]
task 7
Enter array separated by spaces: 5 5
Array:  [5 5]
task 9
Enter positive number: 5
Array:  [5 4 3 2 1 0]
task 10
Enter 2 positive numbers separated by spaces: 5 5
Array:
 [[0.44298238 0.15624694 0.44275734 0.5569569  0.05527516]
 [0.56642914 0.61022939 0.09125643 0.17452599 0.66694652]
 [0.24939278 0.24469541 0.22541932 0.58669074 0.13303195]
 [0.96912481 0.35428333 0.70983546 0.27595076 0.36903394]
 [0.93462883 0.34397217 0.94170359 0.88363714 0.31054259]]
min:  0.055
max:  0.969
mean:  0.452
deviation:  0.274
task 11
Enter positive number: 5
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
task 15
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
task 17
Enter positive number: 5
Array:  [0 1 2 3 4 5

\begin{align*}
  x_{1}+x_{2}+2x_{3}+3x_{4}=1 \\ 
  3x_{1}-x_{2}-x_{3}-2x_{4}=-4 \\ 
  2x_{1}-3x_{2}-x_{3}-x_{4}=-6 \\
  x_{1}+2x_{2}+3x_{3}-1x_{4}=-4
\end{align*}

In [3]:
import numpy as np
    

def solve(a, b):
    b = np.copy(b)
    det = np.linalg.det(a)
    dets = list()

    for i in range(len(a)):
        curr_matrix = np.copy(a)
        curr_matrix[:, i] = b
        current_det = np.linalg.det(curr_matrix)
        dets.append(current_det)

    return np.array(dets) / det

A = np.array([[1, 1, 2, 3],
              [3, -1, -1, -2],
              [2, -3, -1, -1],
              [1, 2, 3, -1]])

B = np.array([1, -4, -6, -4])

X1 = np.linalg.inv(A).dot(B)
X2 = np.linalg.solve(A,B)
X3 = solve(A, B)
print(X1)
print(X2)
print(X3)
print(np.allclose(X1, X2))
print(np.allclose(X1, X3))
print(np.allclose(X2, X3))

[-0.55555556  1.88888889 -2.          1.22222222]
[-0.55555556  1.88888889 -2.          1.22222222]
[-0.55555556  1.88888889 -2.          1.22222222]
True
True
True


\begin{equation*}2(A+B)(2B-A)\end{equation*}

A
$$\begin{bmatrix} 2 & 3 & -1 \\ 4 & 5 & 2 \\ -1 & 0 & 7 \end{bmatrix}$$
B
$$\begin{bmatrix} -1 & 0 & 5 \\ 0 & 1 & 3 \\ 2 & -2 & 4 \end{bmatrix}$$

In [4]:
A = np.array([[2, 3, -1],
              [4, 5, 2],
              [-1, 0, 7]])

B = np.array([[-1, 0, 5],
              [0, 1, 3],
              [2, -2, 4]])

expression = 2*(A+B).dot(2*B-A)
X = expression

print(X)
print(expression)
print(np.allclose(X, expression))

[[   8  -56   54]
 [ -30 -100  146]
 [ 118  -82   28]]
[[   8  -56   54]
 [ -30 -100  146]
 [ 118  -82   28]]
True


\begin{equation*}
  \begin{pmatrix}
    2 & 3 & 1\\
    -1 & 2 & 4\\
    5 & 3 & 0
  \end{pmatrix}
    *X=
  \begin{pmatrix}
    2 & 7 & 13\\
    -1 & 0 & 5\\
    5 & 13 & 21
  \end{pmatrix}
\end{equation*}

In [7]:
A = np.array([[2, 3, 1],
              [-1, 2, 4],
              [5, 3, 0]])
B = np.array([[2, 7, 13],
              [-1, 0, 5],
              [5, 13, 21]])
X = np.round(np.linalg.inv(A).dot(B), 3)
print(X)
print(np.round(np.linalg.solve(A, B), 3))

[[ 1.  2.  3.]
 [ 0.  1.  2.]
 [-0.  0.  1.]]
[[ 1.  2.  3.]
 [ 0.  1.  2.]
 [-0. -0.  1.]]


In [4]:
def task_15():
    try:
        n = int(input('Enter number '))
    except Exception:
        print('Incorrect number')
    else:
        if n >= 0:
            Z = np.zeros((n, n))
            Z[1:-1,1:-1] = 1
            print(Z)
        else:
            print('n is incorrect', n)
task_15()

Enter number 5
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
